#!/usr/bin/env python3
"""Gzip tools/remote/page.html into firmware/platform/hw/webctl_page.h.

    python3 tools/remote/build_page.py            # from the repo root, or anywhere

Output is deterministic (gzip mtime = 0), so the header only changes when the
page does. Run it after every edit of page.html and commit both files.
"""
import gzip, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "page.html")
DST = os.path.normpath(os.path.join(HERE, "..", "..", "firmware", "platform", "hw", "webctl_page.h"))
LIMIT_RAW = 32 * 1024   # flash only ever holds the gzip; raw is a readability guard, not a size limit

raw = open(SRC, "rb").read()
gz = gzip.compress(raw, compresslevel=9, mtime=0)
if len(raw) > LIMIT_RAW:
    sys.exit("page.html is %d bytes, over the %d-byte budget" % (len(raw), LIMIT_RAW))

lines = ["// GENERATED by tools/remote/build_page.py from tools/remote/page.html - do not edit.",
         "// %d bytes raw -> %d bytes gzip. Served as text/html, Content-Encoding: gzip." % (len(raw), len(gz)),
         "#pragma once", "#include <stdint.h>",
         "static const uint32_t WEBCTL_PAGE_GZ_LEN = %d;" % len(gz),
         "static const uint8_t WEBCTL_PAGE_GZ[%d] = {" % len(gz)]
for i in range(0, len(gz), 16):
    lines.append("  " + ",".join("0x%02x" % b for b in gz[i:i+16]) + ",")
lines.append("};")
open(DST, "w").write("\n".join(lines) + "\n")
print("%s: %d raw -> %d gzip -> %s" % (os.path.relpath(SRC), len(raw), len(gz), os.path.relpath(DST)))
